#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

# FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
# WORKDIR /app
# EXPOSE 80
# EXPOSE 443

# FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# COPY ["/MinimalDocker.csproj", "/"]
# RUN dotnet restore "/MinimalDocker.csproj"
# COPY . .
# WORKDIR "/"
# RUN dotnet build "/app/MinimalDocker.csproj" -c Release -o /app/build

# FROM build AS publish
# RUN dotnet publish "/app/MinimalDocker.csproj" -c Release -o /app/publish

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
# ENTRYPOINT ["dotnet", "MinimalDocker.dll"]

#FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
#WORKDIR /app
#COPY . .
#RUN dotnet restore
#RUN dotnet publish -o /app/published-app
#
#FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
#WORKDIR /app
#COPY --from=build /app/published-app /app
#ENTRYPOINT [ "dotnet", "/app/MinimalDocker.dll" ]